<?php

namespace App\Exceptions;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{

    /**
     * A list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

   public function render($request, Throwable $e)
   {
       if ($e instanceof AuthorizationException) {
           throw new ApiException(403, "Forbidden for you");
       }
       return parent::render($request, $e); // TODO: Change the autogenerated stub
   }

}
